### ISSUE TITLE
大哥，你是不是把代码给删了部分啊

### ISSUE THREAD

**Issue by chenxiaocongAI** [ZhenghaoFei/visual_odom#10]
我发现这代码做视觉里程计都不执行bundleAdjustment?还有就是你分成10×10的点，每个格子最多一个点，那就是你一张图片最多100个特征点，我觉得这样也太少了把

**Comment by ZhenghaoFei** [comment]
bundleAdjustment 我确实没有加。 关于特征点数量你可以自己试验一下，平衡速度和性能。
