### ISSUE TITLE
USE_CUDA not work

### ISSUE THREAD

**Issue by BBin1103** [ZhenghaoFei/visual_odom#14]
gpu_build is not replaced by USE_CUDA completely.
![Screenshot from 2020-11-11 16-14-09](https://user-images.githubusercontent.com/38173791/98786408-0628b900-2439-11eb-8f5a-400d8309037d.png)

**Comment by ZhenghaoFei** [comment]
Thank you, all the gpu_build have been replaced by DUSE_CUDA now [commit 4d2b3bb](https://github.com/ZhenghaoFei/visual_odom/commit/4d2b3bb06f71eee91a3c9750a11945fc45dac323)

**Comment by BBin1103** [comment]
@ZhenghaoFei 
2 gpu_build are still there in src/feature.cpp.

**Comment by ZhenghaoFei** [comment]
Thank you! I have fixed the bug and added an OPENCV install guide, let me know if you still can't build the GPU version.
