### ISSUE TITLE
about the kitti estimated results

### ISSUE THREAD

**Issue by weiningwei** [ZhenghaoFei/visual_odom#17]
Hi,Zhenghao! Thanks for sharing your code.
I modified your code in order to save the estimated trajectory.  And I tested the 00-10 sequences of kitti dataset with the modified code. My operations on each sequence are same. But what bothers me is that the results of sequence 04 and 06 are no right. The error is very large. But I think the code can't get such bad results. So I am troubled by the current situation. Have you tested on the other sequence of kitti dataset? Have you encountered such a situation? I could't find the reason of this situation. 
My estimated results of kitti are as follows:
![00](https://user-images.githubusercontent.com/38557780/121358396-2e43b080-c965-11eb-8229-4cd8883bfccb.jpg)
![01](https://user-images.githubusercontent.com/38557780/121358408-300d7400-c965-11eb-8e36-0094565899f9.jpg)
![02](https://user-images.githubusercontent.com/38557780/121358414-30a60a80-c965-11eb-80e2-c6f75dbfd475.jpg)
![03](https://user-images.githubusercontent.com/38557780/121358428-326fce00-c965-11eb-82fd-1b56803ba204.jpg)
![04](https://user-images.githubusercontent.com/38557780/121358433-33086480-c965-11eb-98f1-7d8f95ca280f.jpg)
![05](https://user-images.githubusercontent.com/38557780/121358438-33a0fb00-c965-11eb-9bfc-168e036ad820.jpg)
![06](https://user-images.githubusercontent.com/38557780/121358439-34399180-c965-11eb-8c04-35e8293e08aa.jpg)
![07](https://user-images.githubusercontent.com/38557780/121358443-356abe80-c965-11eb-9105-4bcc6b10b13c.jpg)
![08](https://user-images.githubusercontent.com/38557780/121358446-36035500-c965-11eb-9451-060800764f10.jpg)
![09](https://user-images.githubusercontent.com/38557780/121358449-37348200-c965-11eb-89a7-5deaa6379d5f.jpg)
![10](https://user-images.githubusercontent.com/38557780/121358453-37cd1880-c965-11eb-9ccf-7e317cbd3218.jpg)

**Comment by ZhenghaoFei** [comment]
HI weiningwei,

I just saw your issue, sorry for the late reply.  It seems that the code is working well but 04 and 06 are super challenging. Especially 06 is almost textureless. You can debug with the video to see if features are tracked well, otherwise tune it a little bit. For 04, there might be one single frame leading to a big error in the beginning.

**Comment by ZhenghaoFei** [comment]
I checked with the newest code commit, 04 and 06 seems working well. Can you make sure the calibration .yaml is good?
