### ISSUE TITLE
About the obtained results 

### ISSUE THREAD

**Issue by achrafdjerida** [ZhenghaoFei/visual_odom#3]
Hi professor 

I would first thank you for sharing such important code. I applied this code, however the obtained results on the KITTI are much lower than that published on the SOFT-VO paper. Could you professor explain the reason for that (may be some parts are missing in this code). 

Regards

**Comment by ZhenghaoFei** [comment]
Hi achrafdjerida,

This code is not meant to recover the results published in the paper. Some parts are simplified if you look into the difference between paper and code. If you really want to get similar results as the paper, I would suggest you to improve the feature selection and matching part.

**Comment by achrafdjerida** [comment]
Thank you professor for the clarification . I will try to improve the steps you mentioned .
