### ISSUE TITLE
 CV_StsUnsupportedFormat  " input Parameters in function cvTriangulatePoints"

### ISSUE THREAD

**Issue by OmerElshrief** [ZhenghaoFei/visual_odom#6]
Hello
So I got this error 
"Input parameters must be matrices in function cvTriangulatePoints" 
then I went for the cv.TriangulatePoints implementation then got:
` if( !CV_IS_MAT(projMatr1) || !CV_IS_MAT(projMatr2) ||
      !CV_IS_MAT(projPoints1) || !CV_IS_MAT(projPoints2) ||
      !CV_IS_MAT(points4D) )
      CV_Error( CV_StsUnsupportedFormat, "Input parameters must be matrices" );`
source:  https://github.com/opencv/opencv/blob/master/modules/calib3d/src/triangulate.cpp
then I checked your code at main.cpp, you are passing a vector to the Triangulation function not Mat
`std::vector<cv::Point2f> pointsLeft_t0, pointsRight_t0, pointsLeft_t1, pointsRight_t1; 
cv::triangulatePoints(projMatrl,  projMatrr,  pointsLeft_t0,  pointsRight_t0,  points4D_t0);`

I'am not sure about this but could you please check this.
Thank you

**Comment by ZhenghaoFei** [comment]
Hi Omer,

Which version of OpenCV are you using?
I am using opencv3.4, it works fine and the API doc also says the input can be arrays:
https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#gad3fc9a0c82b08df034234979960b778c

**Comment by OmerElshrief** [comment]
Hello ZhenghaoFei,
Thanks for your replay,  I've tested it with versions 4.2 , 4.1 , 3.2  and I get the same errors 

> current features number after bucketing: 86
calcOpticalFlowPyrLK time: 62.111ms
OpenCV Error: Unsupported format or combination of formats (Input parameters must be matrices) in cvTriangulatePoints, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/calib3d/src/triangulate.cpp, line 64
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/calib3d/src/triangulate.cpp:64: error: (-210) Input parameters must be matrices in function cvTriangulatePoints

>

**Comment by ZhenghaoFei** [comment]
Hi Omer,
I suspected the error is not because of the datatype but perhaps the previous step didn't find any matched points. Which data are you running on? Have you tried the KITTI 00 and dose that work?

**Comment by OmerElshrief** [comment]
> Hi Omer,
> I suspected the error is not because of the datatype but perhaps the previous step didn't find any matched points. Which data are you running on? Have you tried the KITTI 00 and dose that work?

Actually, that's true, The problem was that the Matched features were Zero therefore the Vector Columns were less than 1 so by tracing function calls, the arguments for icvTriangulatePoints function are not matrices :D 
Problem solved by letting the code ignore frames with features less than 4 :D

**Comment by ZhenghaoFei** [comment]
Great to hear! I will also add that into the code at a time. Thanks!

**Comment by SidTeske** [comment]
Hello Omer and ZhenghaoFei,

I get the same error when there are not enough features to track on the frames.
Where in the code did you change to fix this problem? 
I would appreciate any help or advice you can give!

**Comment by ZhenghaoFei** [comment]
> Hello Omer and ZhenghaoFei,
> 
> I get the same error when there are not enough features to track on the frames.
> Where in the code did you change to fix this problem?
> I would appreciate any help or advice you can give!

Hi SidTeske,

I am not sure which line in code you get this error, you can try to check the number of features matched after 
https://github.com/ZhenghaoFei/visual_odom/blob/9405faab47637c6dac671eea843afe24465e8459/src/main.cpp#L149
If the number of features is less than 4 then just skip the after process and assume this frame do not move (return identity rotation and zero translations)

Best,
Zhenghao

**Comment by SidTeske** [comment]
Hello ZhenghaoFei,

Thank you very much! Now it is not crashing! 
When you say "return identity rotation and zero translations", do you mean reset those matrices?
For example, would this work:
```
rotation = cv::Mat::eye(3, 3, CV_64F);
translation = cv::Mat::zeros(3, 1, CV_64F);
```

Thanks again!
Sid

**Comment by ZhenghaoFei** [comment]
> Hello ZhenghaoFei,
> 
> Thank you very much! Now it is not crashing!
> When you say "return identity rotation and zero translations", do you mean reset those matrices?
> For example, would this work:
> 
> ```
> rotation = cv::Mat::eye(3, 3, CV_64F);
> translation = cv::Mat::zeros(3, 1, CV_64F);
> ```
> 
> Thanks again!
> Sid

Hi Sid,

That should work, the main idea is that if you do not get enough features in a frame, you assume this frame do not move relative to the last frame. (Or you can also assume the speed is not changing, which means it moves same rotation and translation as the last frame but that may involve you save the last movement)

Best,
Zhenghao
