### ISSUE TITLE
Use SOFT-SLAM with ROS using ZED camera

### ISSUE THREAD

**Issue by YilmazKadir** [ZhenghaoFei/visual_odom#7]
Hello,
I want to perform SOFT-SLAM on the images published by ZED stereo camera's ROS topics. There is ROS branch, however, I did not really understand how I can use it with ROS. It would be very helpful if you could write a small guide about how we can use this with ROS. Thank you

**Comment by ZhenghaoFei** [comment]
Hi Kdr,

To wrap it with ROS takes some time, you can take a look into the ros branch however I haven't finished it yet.

Some steps you need:
1. subscriber ZED's left&right image topics together.
2. run visual odom code to estimate frame to frame transformation.
3. integrate the frame to frame result.

Best,

**Comment by YilmazKadir** [comment]
Thank you for your response. I will try to follow those steps.
